# Generated by Django 2.1.4 on 2019-01-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_category_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
