# Generated by Django 2.1.4 on 2019-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_category_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='item_size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1, verbose_name='size'),
        ),
    ]
