# Generated by Django 2.1.4 on 2019-01-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190102_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
