# Generated by Django 2.1.4 on 2019-01-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_type_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
