# Generated by Django 2.1.4 on 2019-01-03 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('orders', '0007_auto_20190102_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Type')),
            ],
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='topping_text',
        ),
    ]
