# Generated by Django 2.1.4 on 2019-01-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('orders', '0009_auto_20190102_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='topping_text',
        ),
    ]
