# Generated by Django 2.1.4 on 2019-01-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False    

    dependencies = [
        ('orders', '0010_auto_20190102_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='topping_text',
            new_name='toppings',
        ),
    ]
