# Generated by Django 2.1.4 on 2019-01-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('orders', '0011_auto_20190102_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='toppings',
            new_name='topping_text',
        ),
    ]
